version: '3.8'

services:
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    container_name: minio
    restart: always
    ports:
      - "9000:9000" # API Port
      - "9001:9001" # Console Port
    env_file:
      - ../config/.env # Explicitly load variables from the central .env file
    volumes:
      - ./minio_data:/data # Persists data in a local folder at the project root
    command: server /data --console-address ":9001"